#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 30, 2021 03:08:35 PM +04  platform: Darwin

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


def vp_start_gui():
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    global w, w_win, root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    return (w, top)

class Toplevel1:
    def __init__(self, top=None):
        top.geometry("700x450+366+149")
        top.minsize(72, 15)
        top.maxsize(1440, 762)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#fff")

        self.products = {
            "Iphone": 20,
            "Samsung": 3
        }

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.043, rely=0.089, height=35, relwidth=0.503)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(highlightthickness=3, highlightbackground="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.043, rely=0.022, height=24, width=52)
        self.Label1.configure(background="#fff")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Name''')

        self.Label1_1 = tk.Label(top)
        self.Label1_1.place(relx=0.571, rely=0.022, height=24, width=52)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#fff")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''Count''')


        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.571, rely=0.089, height=35, relwidth=0.174)
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        vcmd = (self.Entry2.register(self.callback))
        self.Entry2.configure(highlightthickness=3, highlightbackground="black",validate='all',
                              validatecommand=(vcmd, '%P'))

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.771, rely=0.089, height=32, width=129)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightthickness=3, highlightbackground="black", command=self.add_product)
        self.Button1.configure(text='''Add Button''')

        self.Listbox1 = tk.Listbox(top)
        self.Listbox1.place(relx=0.043, rely=0.222, relheight=0.573
                            , relwidth=0.446)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(foreground="#000000")
        self.Listbox1.configure(highlightthickness=3, highlightbackground="black")

        self.Listbox1_1 = tk.Listbox(top)
        self.Listbox1_1.place(relx=0.514, rely=0.222, relheight=0.573
                              , relwidth=0.446)
        self.Listbox1_1.configure(background="white")
        self.Listbox1_1.configure(font="TkFixedFont")
        self.Listbox1_1.configure(foreground="#000000")
        self.Listbox1_1.configure(highlightthickness=3, highlightbackground="black")


        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.057, rely=0.822, height=42, width=629)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightthickness=3, highlightbackground="black")
        self.Button2.configure(text='''Pay Button''')

        self.set_products()


    def add_product(self):
        name = self.Entry1.get()
        count = self.Entry2.get()

        if name and count:
            if self.products.get(name):
                self.products[name] = int(self.products.get(name)) + int(count)
            else:
                self.products[name] = count
        else:
            print("Error with Entities")
        self.set_products()

    def set_products(self):
        index = 0
        for name, count in self.products.items():
            self.Listbox1.delete(index)
            self.Listbox1_1.delete(index)
            self.Listbox1.insert(index, name)
            self.Listbox1_1.insert(index, count)

            index += 1

    def callback(self, P):
        if str.isdigit(P) or P == "":
            return True
        else:
            return False

if __name__ == '__main__':
    vp_start_gui()