#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Jun 14, 2021 01:32:19 PM +04  platform: Darwin
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #09573f -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 800x450+287+143
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1440 766
    wm minsize $top 72 15
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "PageThree" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab45 \
        -activebackground #f9f9f9 -activeforeground black -background #09573f \
        -font {-family {American Typewriter} -size 44 -weight bold} \
        -foreground #ad6505 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Personal Information} 
    vTcl:DefineAlias "$top.lab45" "Label1" vTcl:WidgetProc "PageThree" 1
    text $top.tex46 \
        -background #ccc -font TkTextFont -foreground black -height 301 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 329 -wrap word 
    $top.tex46 configure -font "TkTextFont"
    $top.tex46 insert end text
    vTcl:DefineAlias "$top.tex46" "Text1" vTcl:WidgetProc "PageThree" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #09573f \
        -font {-family {Avenir Next Condensed} -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ad6505 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Card Number} 
    vTcl:DefineAlias "$top.lab48" "Label2" vTcl:WidgetProc "PageThree" 1
    entry $top.ent49 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 302 
    vTcl:DefineAlias "$top.ent49" "Entry1" vTcl:WidgetProc "PageThree" 1
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #09573f \
        -font {-family {Avenir Next Condensed} -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ad6505 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Expiry date} 
    vTcl:DefineAlias "$top.lab50" "Label2_1" vTcl:WidgetProc "PageThree" 1
    label $top.lab51 \
        -activebackground #f9f9f9 -activeforeground black -background #09573f \
        -font {-family {Avenir Next Condensed} -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ad6505 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text CVC 
    vTcl:DefineAlias "$top.lab51" "Label2_2" vTcl:WidgetProc "PageThree" 1
    label $top.lab52 \
        -activebackground #f9f9f9 -activeforeground black -background #09573f \
        -font {-family {Avenir Next Condensed} -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ad6505 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Zip code} 
    vTcl:DefineAlias "$top.lab52" "Label2_3" vTcl:WidgetProc "PageThree" 1
    label $top.lab53 \
        -activebackground #f9f9f9 -activeforeground black -background #09573f \
        -font {-family {Avenir Next Condensed} -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ad6505 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text Tip 
    vTcl:DefineAlias "$top.lab53" "Label2_4" vTcl:WidgetProc "PageThree" 1
    entry $top.ent54 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 142 
    vTcl:DefineAlias "$top.ent54" "Entry1_1" vTcl:WidgetProc "PageThree" 1
    entry $top.ent55 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 142 
    vTcl:DefineAlias "$top.ent55" "Entry1_2" vTcl:WidgetProc "PageThree" 1
    entry $top.ent56 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 142 
    vTcl:DefineAlias "$top.ent56" "Entry1_3" vTcl:WidgetProc "PageThree" 1
    entry $top.ent57 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 142 
    vTcl:DefineAlias "$top.ent57" "Entry1_4" vTcl:WidgetProc "PageThree" 1
    entry $top.ent58 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 132 
    vTcl:DefineAlias "$top.ent58" "Entry1_5" vTcl:WidgetProc "PageThree" 1
    button $top.but59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief raised -text {Pay 30$} 
    vTcl:DefineAlias "$top.but59" "Button1" vTcl:WidgetProc "PageThree" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black -background #09573f \
        -font {-family {Avenir Next Condensed} -size 13 -weight bold} \
        -foreground #f00 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Wrong Card Number} 
    vTcl:DefineAlias "$top.lab49" "Label2_5" vTcl:WidgetProc "PageThree" 1
    label $top.lab54 \
        -activebackground #f9f9f9 -activeforeground black -background #09573f \
        -font {-family {Avenir Next Condensed} -size 13 -weight bold} \
        -foreground #f00 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Wrong Expiry date} 
    vTcl:DefineAlias "$top.lab54" "Label2_5_1" vTcl:WidgetProc "PageThree" 1
    label $top.lab55 \
        -activebackground #f9f9f9 -activeforeground black -background #09573f \
        -font {-family {Avenir Next Condensed} -size 13 -weight bold} \
        -foreground #f00 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Wrong CVC} 
    vTcl:DefineAlias "$top.lab55" "Label2_5_2" vTcl:WidgetProc "PageThree" 1
    label $top.lab56 \
        -activebackground #f9f9f9 -activeforeground black -background #09573f \
        -font {-family {Avenir Next Condensed} -size 13 -weight bold} \
        -foreground #f00 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Wrong Zip Code} 
    vTcl:DefineAlias "$top.lab56" "Label2_5_3" vTcl:WidgetProc "PageThree" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab45 \
        -in $top -x 0 -relx 0.1 -y 0 -rely 0.017 -width 0 -relwidth 0.838 \
        -height 0 -relheight 0.14 -anchor nw -bordermode ignore 
    place $top.tex46 \
        -in $top -x 0 -relx 0.538 -y 0 -rely 0.222 -width 0 -relwidth 0.411 \
        -height 0 -relheight 0.669 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.2 -width 0 -relwidth 0.105 \
        -height 0 -relheight 0.076 -anchor nw -bordermode ignore 
    place $top.ent49 \
        -in $top -x 0 -relx 0.051 -y 0 -rely 0.267 -width 302 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.041 -y 0 -rely 0.378 -width 0 -relwidth 0.105 \
        -height 0 -relheight 0.076 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.02 -y 0 -rely 0.556 -width 0 -relwidth 0.105 \
        -height 0 -relheight 0.076 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.238 -y 0 -rely 0.556 -width 0 -relwidth 0.105 \
        -height 0 -relheight 0.076 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.02 -y 0 -rely 0.733 -width 0 -relwidth 0.105 \
        -height 0 -relheight 0.076 -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.444 -width 142 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent55 \
        -in $top -x 0 -relx 0.051 -y 0 -rely 0.444 -width 142 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 0 -relx 0.051 -y 0 -rely 0.622 -width 142 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent57 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.622 -width 142 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent58 \
        -in $top -x 0 -relx 0.051 -y 0 -rely 0.8 -width 132 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but59 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.8 -width 139 -relwidth 0 \
        -height 32 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.163 -y 0 -rely 0.222 -width 0 -relwidth 0.17 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.138 -y 0 -rely 0.4 -width 0 -relwidth 0.17 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 0 -relx 0.1 -y 0 -rely 0.578 -width 0 -relwidth 0.095 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.338 -y 0 -rely 0.578 -width 0 -relwidth 0.12 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

